# GitLab build configuration
image: deboer/icpctools:latest

before_script:
  - echo "No more setup, it's all in docker"

after_script:
  - echo "Post build cleanup"

build:
  stage: build
  script:
#    - ant clean
    - ant build
  artifacts:
    paths:
    - dist/*.*
    expire_in: 1 month

test:
  stage: test
  script:
    - echo "Future tests here"
