# GitLab build configuration
image: openjdk:8

before_script:
  - apt-get update
  - apt-get install -y ant
  - pwd
  - apt-get install -y asciidoctor
  - whereis asciidoctor

after_script:
  - echo "Post build cleanup"

build:
  stage: build
  script:
#    - ant clean
    - ant build
  artifacts:
    paths:
    - BalloonUtility/dist/*.zip
    - CDS/dist/*.zip
    - CoachView/dist/*.zip
    - ContestUtil/dist/*.zip
    - PresAdmin/dist/*.zip
    - PresContest/dist/*.zip
    - ProblemSet/dist/*.zip
    - Resolver/dist/*.zip
    - ToolsWebsite/dist/*.zip
    expire_in: 1 month

test:
  stage: test
  script:
    - echo "Do a test here!"
