# GitLab build configuration
image: openjdk:8

before_script:
  - apt-get update
  - apt-get -y install ant

after_script:
  - echo "Post build cleanup"

build:
  stage: build
  script:
#    - ant clean
    - ant build

test:
  stage: test
  script:
    - echo "Do a test here!"
